opportunity:
  - node/opportunity/**/*
  - runtime/opportunity/**/*

standard:
  - node/standard/**/*
  - runtime/standard/**/*

primitives:
  - primitives/**/*

pallets:
  - pallets/**/*

test:
  - ./**/tests.rs

mock:
  - ./**/mock.rs

github-actions:
  - .github/**/*
