name: "Install Rust for Substrate"
description: "Install Rust configured for Substrate"

inputs:
  toolchain_build: # id of input
    description: "Which version of rust toolchain to use"
    required: false
    default: "nightly-2021-04-22"

runs:
  using: "composite"
  steps:
    - name: Get current arch
      shell: bash
      run: |
        uname -m

    # dependencies handled as part of parent workflow since
    # composite actions do not support conditionals
    # - name: Install Dependencies
    #   shell: bash
    #   run: >
    #     sudo apt install -y git clang curl libssl-dev llvm libudev-dev

    - name: Install Rustup
      shell: bash
      run: |
        curl https://sh.rustup.rs -sSf | sh -s -- -y
        source $HOME/.cargo/env
        rustup default stable
        rustup update stable
        rustup install ${{ inputs.toolchain_build }}
        rustup target add wasm32-unknown-unknown --toolchain ${{ inputs.toolchain_build }}
