ARG RUNTIME_IMAGE=ubuntu:focal

FROM $RUNTIME_IMAGE as runtime

LABEL maintainer="Standard Tech <tech@standard.tech>"
LABEL description="Standard Tech Opportunity Node"

COPY --chmod=u=rwx,go=rx ./opportunity-standalone /usr/local/bin
RUN ldd /usr/local/bin/opportunity-standalone && \
	/usr/local/bin/opportunity-standalone --version

EXPOSE 30333 9933 9944
VOLUME ["/data"]

ENTRYPOINT [ "/usr/local/bin/opportunity-standalone" ]
CMD ["--help"]