version: "3.8"

services:
  opportunity-standalone:
    image: standardprotocol/${NODE}:latest
    container_name: ${NODE}
    volumes:
      - "data-node:/data"
    ports:
      - "30333:30333"
    command: >-
      --chain "${CHAIN}"
      --base-path /data
      --port 30333
      --name "${NODE}"
      --validator

volumes:
  data-node:
    name: "${NODE}-volume"
